// @yarnpkg/lockfile is CJS-only — use the namespace default to interop cleanly
// with Node ESM.
import yarnLockfile from "@yarnpkg/lockfile";
import type { ParsedDependency, LockfileParser } from "./types";

const yarnParse = yarnLockfile.parse;

/**
 * Parse Yarn v1 `yarn.lock` files. Each top-level entry maps a list of
 * specifiers like `lodash@^4.17.0` to an object with `version: "4.17.21"`.
 * The package name is the part before the last `@` in the specifier.
 *
 * Yarn 2+ (Berry) lockfiles use YAML — we'd need separate handling for those;
 * detect by leading `# yarn lockfile v1` vs `# This file is generated by ...`
 * for Berry. For v1 we fall through to JS-yarn's parser.
 */
export const parseYarnLock: LockfileParser = (content) => {
  const out: ParsedDependency[] = [];
  let parsed: { type: string; object?: Record<string, { version?: string }> };
  try {
    parsed = yarnParse(content);
  } catch {
    return out;
  }
  if (parsed.type !== "success" || !parsed.object) return out;

  const seen = new Set<string>();
  for (const [specifier, info] of Object.entries(parsed.object)) {
    const version = info.version;
    if (!version) continue;
    const name = nameFromSpecifier(specifier);
    if (!name) continue;
    const key = `${name}@${version}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ ecosystem: "npm", name, version });
  }
  return out;
};

function nameFromSpecifier(spec: string): string | null {
  // yarn v1 sometimes joins multiple specifiers with ", " — the name is the
  // same across them, so taking the first works.
  const first = spec.split(",", 1)[0]!.trim();
  const at = first.lastIndexOf("@");
  if (at <= 0) return null; // first char `@` means scoped name with no version
  return first.slice(0, at);
}
